drop table if exists User CASCADE;
create table User
(
    userNo bigint generated by default as identity,
    name varchar(255),
    id varchar(255),
    primary key (userNo),
    email varchar(255),
    password varchar(255),
    role varchar(255)
);